- hosts: localhost
  vars_files:
  - vars.yaml

  tasks:
  - name: Create stage directory
    file:
      path: '{{ stage_dir }}/{{ item }}'
      state: directory
    with_items:
      - conf
      - barista
      - httpd-confs
      - srv-solr-data

  - name: install configs from templates directory
    template:
      src: '{{ item.file }}'
      dest: '{{ stage_dir }}/{{ item.dir }}'
    with_items:
      - { file: 'startup.yaml', dir: 'conf' }
      - { file: 'local.yaml', dir: 'barista' }
      - { file: 'docker-compose-amigo.yaml', dir: '' }
      - { file: 'docker-compose-golr.yaml', dir: '' }
      - { file: 'httpd.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-amigo.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-golr.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-barista.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-noctua.conf', dir: 'httpd-confs' }

  - name: Check if repo is staged
    stat:
      path: '{{ stage_dir }}/{{ item }}'
    register: staged_repos 
    with_items:
      - '{{ staged_repos }}'
  - name: Clone repos that are not staged
    git:
     repo: 'https://github.com/geneontology/{{ item.item }}.git'
     dest: '{{ stage_dir }}/{{ item.item }}'
     version: '{{ branch }}'
    with_items:
      - '{{ staged_repos.results }}'
    when: not item.stat.exists

  - name: Check if journal exists 
    stat:
      path: '{{ stage_dir }}/blazegraph.jnl'
    register: journal_result 
  - name: Create journal blazegraph.jnl
    docker_container:
      name: create_journal 
      image: 'minerva:{{ tag }}'
      command: 'java -jar minerva-cli.jar --import-owl-models -j /stage_dir/blazegraph.jnl -f /stage_dir/noctua-models/models'
      auto_remove: true 
      detach: false
      volumes:
        - '{{ stage_dir }}:/stage_dir'
    when: not journal_result.stat.exists

  - name: Check if index exists
    stat:
      path: '{{ stage_dir }}/srv-solr-data/index'
    register: index_result
  - name: Create Solr Index
    docker_container:
      name: create_index
      image: geneontology/golr-autoindex-ontology
      env:
         GOLR_SOLR_MEMORY: 4G
         GOLR_LOADER_MEMORY: 8G
         GOLR_INPUT_ONTOLOGIES: http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl
      auto_remove: true
      detach: false
      volumes:
        - '{{ stage_dir }}/srv-solr-data:/srv/solr/data'
    when: not index_result.stat.exists
